name: CI Logs (Node TS → LogHook)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Type check
        run: |
          if [ -f tsconfig.json ]; then npx tsc --noEmit; else echo "no tsconfig.json"; fi

      - name: Build
        run: |
          if npm run --silent build 2>/dev/null; then echo "build ok"; else echo "no build script"; fi

      # ---- Discord LogHook Notify ----
      - name: Notify LogHook (build result)
        if: always()
        env:
          WEBHOOK: ${{ secrets.LogHook }}   # <- Log-Kanal
          STATUS: ${{ job.status }}
          WF: ${{ github.workflow }}
          BRANCH: ${{ github.ref_name }}
          SHA7: ${{ github.sha }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          TS: ${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at || github.event.repository.updated_at }}
        run: |
          [ -z "$WEBHOOK" ] && echo "::error::Secret 'LogHook' fehlt" && exit 0
          COLOR=$([ "$STATUS" = "success" ] && echo 3066993 || echo 15158332)
          cat > payload.json <<EOF
          { "embeds": [{
              "title": "⚙️ CI $STATUS",
              "description": "**$WF** auf **$BRANCH**\\nCommit: \`${SHA7:0:7}\` von **$ACTOR**",
              "color": $COLOR,
              "fields": [
                {"name":"Repo","value":"$REPO","inline":true},
                {"name":"Branch","value":"$BRANCH","inline":true},
                {"name":"Actor","value":"$ACTOR","inline":true}
              ],
              "timestamp": "$TS"
          }]}
          EOF
          curl -s -H "Content-Type: application/json" -d @payload.json "$WEBHOOK" -o /dev/null -w "HTTP:%{http_code}\n"
